package servlet;

import java.io.IOException;
import java.util.Collection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.JobDataDescr;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import utility.GenericServlet;

import dao.TroikaDao;

/**
 * Servlet implementation class ManageCombo
 */
public class ManageCombo extends GenericServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public ManageCombo() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String first = request.getParameter("first");
		String second = request.getParameter("second");
		
		if("--".equalsIgnoreCase(first)) first = null;
		if("--".equalsIgnoreCase(second)) second = null;
		
		JobDataDescr jobDataDescr = (JobDataDescr)request.getSession().getAttribute("globalEnvironment");
		
		JSONObject json      = new JSONObject();
		JSONArray  elements = new JSONArray();
		TroikaDao troikaDao = new TroikaDao();
		
		try{
			Collection<String> resultDb = null;
			
			if(first!=null && second==null){
				resultDb = troikaDao.getColumnValues(new String[]{first},jobDataDescr.getAmbito() , jobDataDescr.getRadiceJob());
			}else if(first!=null && second!=null){
				resultDb = troikaDao.getColumnValues(new String[]{first, second}, jobDataDescr.getAmbito(), jobDataDescr.getRadiceJob());
			}
			
			if(resultDb!=null) elements.addAll(resultDb);

			json.put("elements", elements);

			request.setCharacterEncoding("UTF8");
			response.setContentType("application/json; charset=UTF-8");
			response.getWriter().write(json.toString());
			//System.out.println("JSON Response: " + json.toString());

/*			String test = "{\"elements\":[\"MENU SERVIZI WIND\",\"FACEBOOK DEALS\",\"SUPER SUMMER PACK\",\"EASY TRAVEL ROMANIA\",\"SUPER ESTATE WIND\",\"PROMO CO-MKTG GENIALLOYD\",\"NOI WIND SOCIAL\",\"DAILY TRAVEL EUROPA\",\"DAILY TRAVEL MONDO\",\"PROMOZIONE TASSA ZERO\",\"PIN PAD\",\"ALL INCLUSIVE UNLIMITED\",\"ALL INCLUSIVE UNLIMITED SIM EDITION\",\"PROMO RICARICA PER ALL INCLUSIVE\",\"ALL INCLUSIVE BUSINESS\",\"PROMO NANOSIM POST\",\"INFOMMS\",\"5 ANNI ALL INCLUSIVE PRE\",\"AGGIORNAMENTO SOFTWARE IPHONE\",\"PROMOZIONE NOI UNLIMITED\",\"PORTA I TUOI AMICI\",\"PROMO LISTINO MEGA UNLIMITED\",\"ALL INCLUSIVE RICARICABILE SPECIAL PACK\",\"RICARICA MINI\",\"PROMO 2 ANNI PER TUTTI\",\"ALL INCLUSIVE WIND PRE\",\"WIN BACK\",\"PROMO SUPER ALL INCLUSIVE\",\"APP. MYWIND\",\"SCONTO CANONE ALL INCLUSIVE\",\"ALL INCLUSIVE DOUBLE\",\"CAMPAGNE WIN BACK\",\"5 ANNI PER TUTTI\",\"INFOSMS\",\"NOI TUTTI SMS BIG\",\"PROMOZIONE MEGA UNLIMITED\",\"PROMO INTERNET NO STOP\",\"DIALOGA INTERNATIONAL\",\"PROMO CO-MKTG - ENELMIA\",\"PROMO CO-MKTG DIPENDENTI ENEL\",\"NOI UNLIMITED\",\"ALL INCLUSIVE PACK\",\"ALL INCLUSIVE SMART 300 SIM EDITION\",\"LISTINO MEGA ORE\",\"INTERNET 1 MESE GRATIS\",\"LISTINO MEGA UNLIMITED\",\"RICARICA AUTOMATICA ATM\",\"COGLI L ATTIMO RICARICA\",\"ALL INCLUSIVE SMART 300 FULL EDITION\",\"PASSA A WIND CON INFOSTRADA\",\"AUTORICARICA INTERNAZIONALE\",\"DISATTIVAZIONE MUSIC CALL\",\"SUPER NOI WIND\",\"SOGLIA TRAFFICO DATI NAZIONALE\",\"NOI WIND UNLIMITED\",\"NOI WIND SMS UNLIMITED\",\"5 ANNI PER TUTTI INTERNET\",\"SCONTO NOI2 UNLIMITED GEN.2013\",\"PROMOZIONE ALL INCLUSIVE SIM EDITION\",\"PROMO SCONTO CANONE 40%\",\"VERIFICA CREDITO RESIDUO\",\"RICARICA ATM NUMERO INCOMPLETO\",\"PROMO RADDOPPIA LA RICARICA_OFFERTA DIP WIND\",\"NOI TUTTI SMS\",\"RICARICA LOTTOMATICA COD.300\",\"RICARICA SISAL COD.300\",\"RICARICA TOTOBIT COD.300\",\"RICARICA EURONET COD.300\",\"50 SPECIAL\",\"PROMO CO-MARKETING\",\"SHOP WIND\",\"ROAMING INTERNAZIONALE\",\"INTERNET NO STOP\",\"ALL INCLUSIVE SMART\",\"ALL INCLUSIVE WIND UNLIMITED PRE\",\"ALL INCLUSIVE BIG\",\"5 ANNI PER TUTTI POSTPAGATO\",\"PROMO INTERNET EVERYWHERE\",\"PROMO INTERNET PER OPZIONI VOCE\",\"NOI TUTTI KING\",\"RIEPILOGO CONTRATTO MOBILE IN ABBONAMENTO\",\"NOI TUTTI BIG\",\"PROMO ALL INCLUSIVE BIG PER NANOSIM\",\"OFFERTA INFOSTRADA\",\"CHIUSURA SERVER DI POSTA\",\"SUPER NOI TUTTI KING\",\"SUPER NOI TUTTI BIG\",\"DAILY TRAVEL X SMARTPHONE EU&USA\",\"WEB TRAVEL WEEKLY MONDO\",\"PORTALE WIND START\",\"NANO SIM\",\"ALL INCLUSIVE PRE\",\"SCONTO CALL YOUR COUNTRY MARZO 2012\",\"IPHONE 5\",\"DAILY TRAVEL X SMARTPHONE MONDO\",\"RICARICA FACEBOOK\",\"ALL INCLUSIVE SMART 400 FULL EDITION\",\"ALL INCLUSIVE SMART 400 SIM EDITION\",\"NOI TUTTI INTERNATIONAL\",\"OPZIONE ALL INCLUSIVE PLUS\",\"SIM WIND RICARICABILE\",\"MOBILE POSTPAGATO\",\"WIND MEETING\",\"ALL INCLUSIVE PLATINUM\",\"RICARICA IVR CARTASÌ\",\"EASY DIALOGA\",\"892 125\",\"SERVIZIO SOPPRESSIONE MASCHERAMENTO ID CHIAMANTE\",\"NOI 2 BIG WEEK\",\"NOI TUTTI X2\",\"ALL INCLUSIVE SILVER\",\"ALL INCLUSIVE GOLD NEW\",\"ALL INCLUSIVE PLATINUM NEW\",\"FACEBOOK SMS\",\"PROMO CROSS SELLING INFOSTRADA\",\"PROMOZIONE ALL INCLUSIVE\",\"OFFERTA DIPENDENTI WIND_ALL INCLUSIVE\",\"NOI TUTTI SMS X2\",\"NOI TUTTI SMS X3\",\"NOI 2 INTERNATIONAL\",\"RICARICA AMERICAN EXPRESS\",\"AGEVOLAZIONI ECONOMICHE\",\"INTERNET MOBILE\",\"EASY ROAMING\",\"PACK NOI ITALY\",\"OPERAZIONE TASSA ZERO\",\"RICARICA SMART\",\"RICARICA CARTASI\",\"NOI TUTTI\",\"RIDUZIONE VELOCITA DI CONNESSIONE DATI\",\"SUPER NOI WIND UNLIMITED\",\"ASSISTENZA GUIDATA\",\"NOI 2 UNLIMITED\",\"BLOCCO SBLOCCO IMEI\",\"NEW GOLD WIND\",\"RINGME SMS\",\"SILVER WIND\",\"PACK NOI WIND\",\"NOI TUTTI X3\",\"RICARICA IVR\",\"PACK NOI WIND BIG\",\"ALL INCLUSIVE GOLD\",\"NOI WIND BIG\",\"PROMO RADDOPPIA LA RICARICA 6 MESI\",\"RICARICA SMS\",\"WIND 9\",\"SALVARUBRICA\",\"REPRICING LOGHI E SUONERIE\",\"RECESSO SIM PREPAGATA\",\"PASSAGGIO DA POST A PRE\",\"INTERNET A TEMPO\",\"MEGA ORE\",\"WIND 4\",\"PROMOZIONE ZERO COSTI FISSI\",\"MEGA 100 ORE\",\"A-MOBILE\",\"BLACKBERRY\",\"FILTRO PROTEZIONE MINORI\",\"RICARICA EURONET\",\"PROMO CARD\",\"ROAMING NO LIMIT\",\"NOI 2 BIG\",\"PACK NOI 2 BIG\",\"CHATRIBÙ SMS\",\"5 TRA NOI\",\"PIENO WIND NEW\",\"ENELMIA\",\"SMS PARTY\",\"INIBIZIONE ID CHIAMANTE\",\"SMS CONSUMATORI\",\"412  1255\",\"WIND 10\",\"PACK NOI2\",\"SPECIAL CARD\",\"PIENO WIND\",\"PROMO RICARICABILE\",\"EASY TRAVEL INTERNET\",\"CALL YOUR COUNTRY\",\"NOI WIND MESSAGGI\",\"PROMO 5X6\",\"TRIAL MOBILE\",\"ATTIVITÀ STREET-MARKETING\",\"MEGA UNLIMITED\",\"WIND EASY TRAVEL EUROPA\",\"NORMATIVA RAEE\",\"WIND EASY TRAVEL MONDO\",\"PROGRAMMA LOYALTY ALL INCLUSIVE CARD\",\"SMS BENEFICENZA\",\"ALLARME SOGLIA\",\"SUPER SUMMER RICARICA\",\"TJ NET GIOCHI\",\"REGOLAMENTAZIONE UE: TRAFFICO DATI MOBILE\",\"MICRO SIM\",\"SUMMER PACK\",\"SUPER SMARTPHONE\",\"RINNOVO PIENO SMS\",\"OPZIONE INTERNAZIONALE\",\"ROAMING 50\",\"WIND 5 NEW PRE\",\"WIND SENZA SCATTO NEW\",\"WIND 12\",\"SERVIZI EXTERNAL PROVIDER\",\"NOI TRE NEW\",\"WIND SENZA SCATTO\",\"WIND CARD\",\"RIMODULAZIONE COSTO PT OPZIONI NOI\",\"PROMOZIONE CANONE ZERO\",\"PIENO SMS\",\"SUPER SENZA SCATTO\",\"NOI WIND ROAMING\",\"FAMILY PACK\",\"SIM 64K SAT\",\"PROMO 5X3 VERSO TUTTI\",\"PROMOZIONE 10X3\",\"SCRATCH DANNEGGIATA ILLEGIBILE\",\"ALL INCLUSIVE PLUS\",\"WIND 6 SMS\",\"RICARICA ON LINE\",\"RICARICA PREMIO\",\"AUTOPROVISIONING\",\"TELEFONO INCLUSO\",\"RICARICA VIRTUALE DEALER\",\"WIND 5 - TRASFERIMENTO AL 156\",\"RICARICA BONUS\",\"DURATA OPZIONE 30 GG.\",\"WIND 5\",\"BLOCCO SERVIZI SENSIBILI\",\"SPECIAL CARD CONTENUTI\",\"RINNOVO PIENO WIND\",\"RIMODULAZIONE NOI WIND SMS\",\"DISATTIV. MASSIVA MOROSI FRODE MOBILE\",\"INDIRIZZ NR. VERDI O DEDICATI MOBILE\",\"INVIO BROCHURE MOBILE\",\"PROMO SUPER INTERNET PACK\",\"PROMO SUPER INTERNET UNLIMITED\",\"PROMO SUPER NOI TUTTI\",\"SMS\",\"SIM SILENTI\",\"DUMMY: CLIENTE PRIVO DI ANAGRAFICA\",\"PT AUTORICARICA USCENTE PRE\",\"PT AUTORICARICA USCENTE POST\",\"PAGO WIND\",\"EASYRICARICA\",\"NOI WIND VOCE\",\"PRENOTAZIONE UMTS\",\"MNP\",\"DISATTIVAZ. SIM SILENTI\",\"TERMINALI SIM\",\"COMUNICAZIONE MSISDN\",\"SECRET NICKNAME MMS\",\"MNP RIFIUTO WIND\",\"MNP RIFIUTO DONATING\",\"WIND IDENTITY\",\"WAP\",\"SEGRETERIA TELEFONICA\",\"MANCATO INCREMENTO CREDITO\",\"MYWIND\",\"PROMO MNP\",\"RICARICA ATM\",\"SCRATCH CARD\",\"SCRATCH UTILIZZATA\",\"MUSICCALL\",\"PROMOZIONE MINUTI&MINUTI\",\"RICARICA TOTOBIT\",\"PIANI TARIFFARI MOBILE\",\"NOI ITALY\",\"CHIAMATE ROAMING ITZ\",\"WEB TRAVEL WEEKLY EUROPA E USA\",\"FUNZIONAMENTO SERVIZIO KANTOO - ENGLISH SMS\",\"ATTIVAZIONE SERVIZIO KANTOO - ENGLISH SMS\",\"DISATTIVAZIONE SERVIZIO KANTOO - ENGLISH SMS\",\"SUPER NOI TUTTI\",\"SUPER NOI TUTTI X3\",\"TWITTER SMS\",\"CASA REWIND MOBILE\",\"SUPER RICARICA\",\"RIMODULAZIONE CALL YOUR COUNTRY\",\"MIGRAZIONE VERSO SUPER SENZA SCATTO\",\"RICARICA AUTOMATICA WEB\",\"PROMOZIONE PROVA SMS\",\"RINGME\",\"RICARICA SISAL\",\"SECRET NICKNAME SMS\",\"DEDICA\",\"MMS\",\"PENSACITU\",\"FOLLOWWIND\",\"SUONERIE LOGHI E PICTURE SMS\",\"WAP DOWNLOAD\",\"PASSAGGIO DA PRE A POST\",\"PRONTO RICARICA CLUB RICARICA\",\"ALL INCLUSIVE SMART SIM EDITION\",\"ALL INCLUSIVE SILVER SIM EDITION\",\"ALL INCLUSIVE GOLD SIM EDITION\",\"ALL INCLUSIVE PLATINUM SIM EDITION\",\"PUNTI VENDITA WIND MOBILE\",\"REVOCA DISDETTA MOBILE\"]}";
			response.getWriter().write(test..replace("À", "A'").replace("Ù", "U'").replace("Ì", "I'").);
			System.out.println("JSON Response: " + test);
*/
		}catch (Exception jse){ 
			jse.printStackTrace();
			throw new IOException(jse.getMessage());
		}
	}

}
